### ISSUE TITLE
apex::iter namespace should be used to implement customization point objects for apex::mixin::iterator

### ISSUE THREAD

**Issue by bruxisma** [netlify/apex#12]
The advent of CPOs (customization point objects) for C++ dispatching means that `apex::mixin::iterator` could technically be implemented entirely by way of CPOs. In addition to ranges related traits (e.g., `incrementable_traits`, we can also rely on `iter::next`, `iter::prev`, etc. to see if a type meets the given interface for a specific iterator), having `iter::` specific CPOs would allow us to also eventually wrap iterators into type erased iterator APIs. This will also make hooking into ranges easier in the future.

**Comment by slurps-mad-rips** [comment]
Although `apex::iter::read_from` and `apex::iter::write_into` have not actually been implemented yet, the rest of the operations are now available. Once `read_from` and `write_into` are available, this issue can be closed.
